//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mix_acticle
    {
        public int ActicleID { get; set; }
        public Nullable<int> CatContentID { get; set; }
        public string ActicleTitle { get; set; }
        public string ActicleCopyright { get; set; }
        public Nullable<System.DateTime> ActicleDate { get; set; }
        public string ActicleAbstract { get; set; }
        public string ActicleContain { get; set; }
    
        public virtual mix_categorycontent mix_categorycontent { get; set; }
    }
}
