//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mix_category
    {
        public mix_category()
        {
            this.mix_categorycontent = new HashSet<mix_categorycontent>();
        }
    
        public int CatID { get; set; }
        public string CatName { get; set; }
    
        public virtual ICollection<mix_categorycontent> mix_categorycontent { get; set; }
    }
}
